version: '3.3'

services:
 web:
  image: mcublog/python_app:1.0
  build:
   context: .
  ports:
  - 8000:5000
  depends_on:
  - redis
 redis:
  image: "redis:alpine"
  command:
    - redis-server
    - /home/redis/redis.conf
  volumes:
    - ./redis/redis.conf:/home/redis/redis.conf
    - ./redis/appendonly.aof:/data/appendonly.aof
